; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:atlas]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
test_filter = test_atlas
lib_deps = 
	adafruit/Adafruit ICM20X@^2.0.7
	jgromes/RadioLib@^7.6.0
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/SdFat - Adafruit Fork@^2.3.103
	madhephaestus/ESP32Servo@3.0.9

[env:base_station]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
test_filter = test_base_station
lib_deps = 
	jgromes/RadioLib@^7.6.0
	adafruit/SdFat - Adafruit Fork@^2.3.103
	madhephaestus/ESP32Servo@3.0.9

[env:native_lib_test]
platform = native
test_filter = test_native
lib_ignore = IMU
test_framework = unity
lib_deps = madhephaestus/ESP32Servo@3.0.9

[env:native_sitl]
platform = native
build_src_filter = +<../sitl/> -<src/>
lib_ignore = IMU
extra_scripts = post:run_build_to_csv.py
lib_deps = madhephaestus/ESP32Servo@3.0.9
